// Generated by Wrangler by running `wrangler types`

export interface Env {
	AIBTCDEV_CACHE_KV: KVNamespace;
	HIRO_API_KEY: string;
	SUPABASE_URL: string;
	SUPABASE_SERVICE_KEY: string;
	BNS_API_DO: DurableObjectNamespace<import('./src/index').BnsApiDO>;
	HIRO_API_DO: DurableObjectNamespace<import('./src/index').HiroApiDO>;
	STX_CITY_DO: DurableObjectNamespace<import('./src/index').StxCityDO>;
	SUPABASE_DO: DurableObjectNamespace<import('./src/index').SupabaseDO>;
	CONTRACT_CALLS_DO: DurableObjectNamespace<import('./src/index').ContractCallsDO>;
}
