// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`
import { KVNamespace } from "@cloudflare/workers-types";

interface CloudflareBindings {
  AIBTCDEV_CACHE_KV: KVNamespace;
  HIRO_API_KEY: string;
}
