name: Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Ship Ship Ship
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Test Endpoints
        run: |
          chmod +x tests/test_endpoints.sh
          ./tests/test_endpoints.sh https://cache.aibtc.dev
