name: Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Ship Ship Ship
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            HIRO_API_KEY
            SUPABASE_URL
            SUPABASE_SERVICE_KEY
          env:
            HIRO_API_KEY: ${{ secrets.HIRO_API_KEY }}
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
